<template>
    <div class="brands-container">
        <Nav />
        <Banner />
        <div class="wp1360">

            <div class="title hsHeader">
                <h3>咨询流程</h3>
            </div>
            <div class="cont">
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛咨询服务流程采用国际先进的管理变革模型IDEAL模型，它是由SEI在PDCA循环理论上研究得出的。专门用于指导企业逐步提升管理能力。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">IDEAL模型关注于建立一个持续改善机制，它包含5个阶段:初始化阶段(Initiating),诊断阶段(Diagnosing),建立阶段(Establishing),行动阶段(Acting),经验教训总结阶段(Learning)。每个阶段由多个活动组成，IDEAL正是采用这五个阶段的首字母命名的。</span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="IDEAL模型" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="IDEAL模型" width="435" height="290" longdesc="http://www.huasaiinfo.com/images/ideal_full_color.gif" src="http://www.huasaiinfo.com/images/ideal_full_color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">IDEAL模型为我们提供了以各浅显易懂的、标准的、流程改善的方法，它详细描述流程改善的步骤，指导企业建立一个长期的、持续的流程改善机制。经过广泛应用证明IDEAL模型能够为企业带来巨大价值。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">以下详细描述IDEAL各阶段活动</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;">1. 起始阶段 (Initiating)</strong></span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="initiating" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="initiating" width="253" height="86" longdesc="http://www.huasaiinfo.com/images/initiating.color.gif" src="http://www.huasaiinfo.com/images/initiating.color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">本阶段是 IDEAL 模式的起点，在这个阶段，要构建流程改善的基础架构，定义组织内每个角色及其职责，根据组织的愿景、策略及过去的经验，拟定改进计划。 可分为下面四个部分：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(1) 变革的刺激 (Stimulus for Change)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">对企业而言，了解组织变革的诱因是非常重要的。 它可能来自内部管理阶层的命令，亦可能是一个突发事件，不论这个刺激是什么，它都可能影响所投入的人力，执行的方法及最后的结果。 为改变而改变，通常不会有明显的改善；唯有要求变革的动机越强，成功的机率才越大。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(2) 设定工作内容 (Set Context)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">一旦了解变革的动机，管理阶层就必须设定工作内容。 工作内容表示要改进哪些问题以及如何改进，需符合组织的策略和经营目标，变革是否影响其他的工作，所得到的回收是多少。工作的内容及可能的影响会随着变革的进行而越来越明显，但我们尽可能在初期定义越清楚越好。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(3) 高层的支持 (Build Sponsorship)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">来自高层的支持是变革的重要因素之一，尤其在变革初期，常会面对许多不确定的因素及混乱的情况，管理阶层的支持在初期是非常重要的。 尤其是管理层需要为管理改善投入足够的资源，这对是否能取得成功尤其重要。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(4) 建立基础架构 (Charter infrastructure)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">一旦变革的的动机和工作内容都已了解，高层亦承诺支持这项行动，便可建立一个机制来管理变革的实施细节。 这个机制可能是临时或永久的，它的大小和复杂度亦随着变革的特性而变，对于一个小的变革，可能只需要一个兼职的员工；对于一个大的变革，可能需要整个组织 2% - 3% 的人力。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;">2. 诊断阶段 (Diagnosing)</strong></span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="diagnosing" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="diagnosing" width="157" height="126" longdesc="http://www.huasaiinfo.com/images/diagnosing.color.gif" src="http://www.huasaiinfo.com/images/diagnosing.color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">诊断目前的工作模式，由此确定管理改善的工作目标。 首先要确定用于诊断的检查标准，以确保流程改善的要点与企业的战略目标一致。 然后规划并收集企业运营相关信息，包括人力资源水平、历史习惯、强项、弱项等，最后制作诊断结果及改进建议报告。 主要分为下面两个部分工作：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(1) 了解目前的状况及期望的目标 (Characterize Current &amp; Desired Status)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">了解目前的状况及期望的目标就好像旅程的起点与终点，主要专注在与变革相关的项目上。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(2) 发展建议方案 (Develop Recommendations)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">诊断工作通常由华赛公司具有丰富经验的专家在企业管理人员的协助下进行，后续改善工作将在此调查结果的基础上开展。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;">3. 建立阶段 (Establishing)</strong></span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="establishing" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="establishing" width="197" height="115" longdesc="http://www.huasaiinfo.com/images/establishing.color.gif" src="http://www.huasaiinfo.com/images/establishing.color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">拟定一个计划，说明需如何达到目标。 在此阶段企业需决定改善的行动和其优先顺序，并寻找适当的解决方案，将起始阶段所定义的一般流程改善目标细化为更为明确的目标，并配置行动所需的资源。 可分为下面三个部分：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(1) 设定优先顺序 (Set priorities)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">根据问题的影响大小、紧急程度、可用的资源等各方面的因素设定改进的优先顺序</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(2) 研究可行的方法 (Develop Approach)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">结合对工作的了解及优先顺序拟定改进策略方案。 技术方面要考虑引入新的技术、方法和知识；非技术方面要考虑：企业文化、可能遇到的阻力、管理者的支持力度及市场环境的影响。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(3) 规划行动方案 (Plan Actions)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">总体方案确定后，就可以规划详细的执行计划，它包含进度安排、工作内容和里程碑、资源、角色和职责、度量、风险管理策略等等。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;">4.行动阶段(Acting)</strong></span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="acting" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="acting" width="130" height="236" longdesc="http://www.huasaiinfo.com/images/acting.color.gif" src="http://www.huasaiinfo.com/images/acting.color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">实施行动计划。 持续细化行动计划，逐一解决诊断阶段所发现的问题。 试行解决方案后，选出最适合企业的方案，最后全面推广和实施。 可分为下面四个部分：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(1) 提出解决方案 (Create Solution)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">结合所有可用的资源，提出一个可行的最佳方案，这些资源可能是工具、流程、人员，或者是新的技术，外界的资源。 这个方案可能非常复杂，通常由流程改善工作小组共同研究后提出。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(2) 试行可能的解决方案 (Pilot/Test Solution)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">将设计的解决方案在小范围内试行和测试，确保方案的有效性，收集方案的建议。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(3) 修正解决方案 (Refine Solution)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">根据试行中所得到的经验和改善建议，修正解决方案，直到达成一个满意的方案。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(4) 推展解决方案 (Implement Solution)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">一旦解决方案经过验证是可行的，就可以将其推广至整个组织。 可使用不同的方法来执行，如由上而下 (Top-down) ：从组织的最高层往下推广；及时 (just-in-time) ：一个专案接着一个专案推动。 没有哪一种方法是最好的，根据组织的环境和改善的特性来决定使用哪种方法。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><strong style="margin: 0px; padding: 0px;">5.经验教训总结阶段(Learning)</strong></span></p>
                <p style="margin-top: 1em; margin-bottom: 1em; padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(51, 51, 51); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; unicode-bidi: embed; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">　　</span><a class="image" title="learning" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);"><img alt="learning" width="158" height="113" longdesc="http://www.huasaiinfo.com/images/learning.color.gif" src="http://www.huasaiinfo.com/images/learning.color.gif" style="margin: 0px; padding: 0px; border: 0px solid rgb(51, 51, 51);" /></a></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">总结过程改进的经验和教训，以供 IDEAL 模式下一个循环时使用，确保所使用的策略、方法及组织架构是最佳的；修正或调整改善流程，使下一循环的流程改善工作更有效率。 可分为下面两个部分：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(1) 分析与验证 (Analyze and Validate)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">在这个过程中，我们要检讨下列问题，改善的努力是否达到预期的目标？哪些问题得到了改善？哪些方面的工作变得更有效率了？在整个过程所获得的经验教训，都要进行收集，分析，汇总及记录成文件。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">(2) 提出未来行动建议 (Propose Future Actions)</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">根据分析与验证的结果，提出未来的改善方案建议。</span></p>
                <p><br /></p>
            </div>
            <div class="title hsHeader">
                <h3>服务特色</h3>
            </div>
            <div class="cont">
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">对于任何一家专业服务机构而言，根据目标客户群的需求特点形成各自的服务特色是其能否在行业领域内长期处于领先地位的关键要素。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">准备创建华赛时，创始人便曾经对国际著名咨询机构的服务能力和服务特点进行过分析。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">在中国经济高速发展的今天，大多数研发企业的业务发展迅速，规模迅速扩大，企业面临巨大的挑战和机会。华赛致力于提升企业研发能力和管理能力，协助企业打造其核心竞争力。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛创建伊始，便注重于将“为客户创造价值”的理念与服务方式设计、员工技能培训和专业服务实践相结合，而专业服务实践又使得华赛的服务特色日渐丰富：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※华赛有大约60％的项目经验是战略咨询与流程改善相结合的；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※华赛有大约40％的项目经验涉及人力资源管理改善；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※华赛有大约30％的项目经验涉及组织架构调整、企业管理变革和流程自动化建设；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※华赛有大约10％的项目经验涉及融资管理和企业上市辅导。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">……</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">多样化的业务领域，使华赛初步具备快速理解企业业务模式及其所面临的各种问题，并能按照不同的改进需求进行有针对性的咨询服务的能力，也使得华赛的服务团队能够结合多个方面的因素提出综合的解决方案，更有效的帮助企业达成业务目标，实现快速发展。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛具有为不同规模、不同业务领域、不同运营模式的企业提供咨询服务的经验；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛与众多国内外企业建立了良好的战略合作伙伴关系；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛的客户满意度极高，因此回头率最高，华赛与大多数客户建立了长期合作关系；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">华赛为客户提供从市场分析到内部管理人员培养、研发技术和管理改善、到融资上市辅导等全方位的服务。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">大量的国内咨询服务实践使华赛提练出属于自己的服务特点：</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※强调学习——咨询师总有一天要离开企业，企业最终要靠自身能力持续改善，管理层综合素质的提升尤为重要；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※强调沟通——在独立分析和判断的基础上以大量、不同形式的沟通方式形成对客户问题的深刻理解；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※从问题出发——从问题出发的咨询服务模式目标明确、验收标准清晰，最大程度确保为企业带来实效，避免流于形式；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※专家支持——在不同行业领域内根据解决问题的深度和行业特点，构建外部专家支持体系，包括与国际著名咨询公司合作；</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※方案灵活——不生搬硬套，也不追求完美。为企业设计“最适合”、“最轻便”、“最灵活”的解决方案。</span></p>
                <p style="padding: 0px; text-indent: 24px; line-height: 23px; color: rgb(102, 102, 102); font-family: 宋体, &#39;Arial Narrow&#39;; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 0);">※强调总结——定期的总结可以明确工作中的不足，展示已经取得得成效，激励变革士气，明确后续工作方向。</span></p>
                <p><br /></p>
            </div>
            <div class="title hsHeader">
                <h3>定制化服务</h3>
            </div>
        </div>

        <Footer class="top" />
    </div>
</template>
  
  <script>
import { addBrand } from '@/api/index.js'

export default {
    name: 'Brands',
    data() {
        return {}
    },
    mounted() {},
    methods: {},
}
</script>
  
  <style lang="less" scoped>
</style>